
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module FPGA_Footsies_V4(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS,

	//////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
	inout 		    [35:0]		GPIO
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
wire divided_clk;
wire [2:0] key_value;
wire key_pressed;
wire keypad_row;        // Single row output
wire [2:0] keypad_cols; // 3 column inputs

assign GPIO[10] = keypad_row;

// Assign keypad columns from GPIO inputs (3 pins)
assign keypad_cols[0] = GPIO[18];
assign keypad_cols[1] = GPIO[20];
assign keypad_cols[2] = GPIO[22];


Clock_Divider #(
//    .division(100000),
    .W(32)
) clk_div_inst (
    .clk_in(CLOCK_50),
    .clk_bypass(SW[1]),    // Use SW[1] for bypass
    .button(~KEY[0]),        // Use SW[2] as manual clock in bypass mode
    .reset(SW[3]),      // Active high reset
    .clk_out(divided_clk)
);


// 1x3 Keypad Interface
keypad_1x3 keypad_inst (
    .clk(divided_clk),
    .rst_n(1'b1),
    .col(keypad_cols),
    .row(keypad_row),
    .button_out(key_value),
    .key_valid(key_pressed)
);

game_core twoplayers(
	.clock(CLOCK_50),
	.clock_bypass(SW[1]),
	.clock_manual_button(~KEY[0]),
	.reset(SW[3]),
	.switch_hitbox(SW[0]),
	.player1_left(~KEY[3]),
	.player1_right(~KEY[1]),
	.player1_attack(~KEY[2]),
	.player2_left(key_value[0]),
	.player2_right(key_value[2]),
	.player2_attack(key_value[1]),
	.VGA_red(VGA_R),
	.VGA_blue(VGA_B),
	.VGA_green(VGA_G),
	.VGA_sync(VGA_SYNC_N),
	.VGA_clock(VGA_CLK),
	.VGA_Hsync(VGA_HS),
	.VGA_Vsync(VGA_VS),
	.VGA_blank(VGA_BLANK_N),
	.health_p1({LEDR[9],LEDR[8],LEDR[7]}),
	.health_p2({LEDR[2],LEDR[1],LEDR[0]})
);


endmodule
