//=======================================================
//  This code is generated by Terasic System Builder
//  Modified for single row (1x3) keypad
//=======================================================
module Keypad(
	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,
	//////////// LED //////////
	output		     [9:0]		LEDR,
	//////////// SW //////////
	input 		     [9:0]		SW,
	//////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
	inout 		    [35:0]		KeyGPIO
);

//=======================================================
//  REG/WIRE declarations
//=======================================================
wire divided_clk;
wire [2:0] key_value;
wire key_pressed;
wire keypad_row;        // Single row output
wire [2:0] keypad_cols; // 3 column inputs

//=======================================================
//  GPIO Pin Assignments
//=======================================================
// Assign single keypad row to GPIO output (1 pin)
assign KeyGPIO[10] = keypad_row;

// Assign keypad columns from GPIO inputs (3 pins)
assign keypad_cols[0] = KeyGPIO[18];
assign keypad_cols[1] = KeyGPIO[20];
assign keypad_cols[2] = KeyGPIO[22];

//=======================================================
//  LED Display Logic
//=======================================================
// Display key value on LEDs 3-0, key_pressed on LED 9
assign LEDR[2:0] = key_value;
assign LEDR[9] = key_pressed;

//=======================================================
//  Module Instantiations
//=======================================================

// Clock Divider - divide by 100000 for single row scanning (faster since less scanning needed)
Clock_Divider #(
    .division(100000),
    .W(32)
) clk_div_inst (
    .clk_in(CLOCK_50),
    .clk_bypass(SW[1]),    // Use SW[1] for bypass
    .button(SW[2]),        // Use SW[2] as manual clock in bypass mode
    .reset(1'b0),      // Active high reset
    .clk_out(divided_clk)
);

// 1x3 Keypad Interface
keypad_1x3 keypad_inst (
    .clk(divided_clk),
    .rst_n(1'b1),
    .col(keypad_cols),
    .row(keypad_row),
    .button_out(key_value),
    .key_valid(key_pressed)
);

endmodule
