
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module FPGA_Footsies_Final(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS,

	//////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
	inout 		    [35:0]		GPIO
);

wire divided_clk;
wire [2:0] key_value;
wire key_pressed;
wire keypad_row;
wire [2:0] keypad_cols;
wire [15:0] lfsr_out;

assign GPIO[10] = keypad_row;
assign keypad_cols[0] = GPIO[18];
assign keypad_cols[1] = GPIO[20];
assign keypad_cols[2] = GPIO[22];

Clock_Divider #(
    .W(32)
) clk_div_inst (
    .clk_in(CLOCK_50),
    .clk_bypass(SW[1]),
    .button(~KEY[0]),
    .reset(SW[3]),
    .clk_out(divided_clk)
);

// 1x3 Keypad Interface
keypad_1x3 keypad_inst (
    .clk(divided_clk),
    .rst_n(~SW[3]),  // Active low reset
    .col(keypad_cols),
    .row(keypad_row),
    .button_out(key_value),
    .key_valid(key_pressed)
);


CPU_logic cpu(
	.clock(CLOCK_50),
	.clock_bypass(SW[1]),
	.reset(1'b0),
	.clock_manual_button(~KEY[0]),
	.lfsr_output(lfsr_out)
);

game_fsm game(
	.clk_50(CLOCK_50),
	.reset(SW[5]),
	.switches(SW),
	.keys(~KEY),
	.keypad_p2(key_value),
	.cpu_p2({lfsr_out[15],lfsr_out[14],lfsr_out[13]}),
	
	.vga_clk(VGA_CLK),
   .vga_blank_n(VGA_BLANK_N),
   .vga_sync_n(VGA_SYNC_N),
   .vga_hs(VGA_HS),
   .vga_vs(VGA_VS),
   .vga_r(VGA_R),
   .vga_g(VGA_G),
   .vga_b(VGA_B),
		
);


//=======================================================
//  Structural coding
//=======================================================



endmodule
