
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module FPGA_Footsies(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS
);

wire clk_25MHz;
wire clk_60MHz;
wire [2:0] sprite_state; 
wire [9:0] sprite_x, sprite_y;
wire [7:0] sprite_color;
wire inside_sprite = (pixel_x >= sprite_x) && (pixel_x < sprite_x + 64) &&
                     (pixel_y >= sprite_y) && (pixel_y < sprite_y + 240);
wire [9:0] hitbox_x1, hitbox_x2, hitbox_y1, hitbox_y2;
wire [9:0] hurtbox_x1, hurtbox_x2, hurtbox_y1, hurtbox_y2;
wire hitbox_active, hurtbox_active;
wire switch_hitbox = SW[0];  // switch for hitbox on/off, can be changed   
wire [7:0] background_color = 8'b111_111_11; // will be changed
wire [7:0] color_out;
wire [9:0] pixel_x, pixel_y;

// No need for now, but inside wires will be needed for collision check //
wire inside_hurtbox = hurtbox_active &&
                      (pixel_x >= hurtbox_x1 && pixel_x < hurtbox_x2) &&
                      (pixel_y >= hurtbox_y1 && pixel_y < hurtbox_y2);

wire inside_hitbox = hitbox_active &&
                     (pixel_x >= hitbox_x1 && pixel_x < hitbox_x2) &&
                     (pixel_y >= hitbox_y1 && pixel_y < hitbox_y2);
// -----------------------------------------------------------------------
	
// Hurtbox & Hitbox have 2-pixel thickness instead of covering the all sprite
wire hurtbox_edge = draw_debug && hurtbox_active &&
    (
        (pixel_x >= hurtbox_x1 && pixel_x < hurtbox_x1 + 2) ||
        (pixel_x >= hurtbox_x2 - 2 && pixel_x < hurtbox_x2) ||
        (pixel_y >= hurtbox_y1 && pixel_y < hurtbox_y1 + 2) ||
        (pixel_y >= hurtbox_y2 - 2 && pixel_y < hurtbox_y2)
    ) &&
    (pixel_x >= hurtbox_x1 && pixel_x < hurtbox_x2) &&
    (pixel_y >= hurtbox_y1 && pixel_y < hurtbox_y2);

wire hitbox_edge = draw_debug && hitbox_active &&
    (
        (pixel_x >= hitbox_x1 && pixel_x < hitbox_x1 + 2) ||
        (pixel_x >= hitbox_x2 - 2 && pixel_x < hitbox_x2) ||
        (pixel_y >= hitbox_y1 && pixel_y < hitbox_y1 + 2) ||
        (pixel_y >= hitbox_y2 - 2 && pixel_y < hitbox_y2)
    ) &&
    (pixel_x >= hitbox_x1 && pixel_x < hitbox_x2) &&
    (pixel_y >= hitbox_y1 && pixel_y < hitbox_y2);
// --------------------------------------------------------------------------
assign color_out = hitbox_edge  ? 8'hE0 :     // red
                   hurtbox_edge ? 8'h03 :     // blue
                   sprite_pixel ? sprite_color :
                   background_color;

Clock_Divider #(.division(2)) clock_vga(
	.clk_in(CLOCK_50),
	.clk_bypass(1'b0),
	.button(1'b0),
	.reset(1'b0),
	.clk_out(clk_25MHz)
);

Clock_Divider #(.division(833334)) clock_fsm(
	.clk_in(CLOCK_50),
	.clk_bypass(SW[1]),
	.button(~KEY[0]),
	.reset(1'b0),
	.clk_out(clk_60MHz)
);

Sprite_FSM sprite1(
	.clk(clk_60MHz),
	.reset(1'b0),
	.left(~KEY[3]),
	.right(~KEY[1]),
	.attack(~KEY[2]),
	.state(sprite_state)
);

Sprite_renderer render1(
	.clk(clk_60MHz),
	.state(sprite_state),
	.sprite_x(sprite_x),
	.sprite_y(sprite_y),
	.sprite_color(sprite_color)
);

Sprite_boxes boxes1 (
    .state(sprite_state),
    .sprite_x(sprite_x),
    .sprite_y(sprite_y),
    .hitbox_x1(hitbox_x1),
    .hitbox_x2(hitbox_x2),
    .hitbox_y1(hitbox_y1),
    .hitbox_y2(hitbox_y2),
    .hurtbox_x1(hurtbox_x1),
    .hurtbox_x2(hurtbox_x2),
    .hurtbox_y1(hurtbox_y1),
    .hurtbox_y2(hurtbox_y2),
    .hitbox_active(hitbox_active),
    .hurtbox_active(hurtbox_active)
);

vga_driver vga(
	.clock(clk_25MHz),
        .reset(1'b0),
	.color_in(color_out),
	.next_x(pixel_x),
	.next_y(pixel_y),
	.hsync(VGA_HS),
	.vsync(VGA_VS),
	.red(VGA_R),
	.green(VGA_G),
	.blue(VGA_B),
	.sync(VGA_SYNC_N),
	.clk(VGA_CLK),
	.blank(VGA_BLANK_N)
);

endmodule
